# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               OpenStreetMap Carto Tutorials
tagline:             'Unofficial documentation'
description:         'Unofficial tutorials for <a href="https://github.com/gravitystorm/openstreetmap-carto" target="_blank">openstreetmap-carto</a>.'
url:                 http://ircama.github.io/osm-carto-tutorials
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ircama
  url:               http://ircama.github.io/osm-carto-tutorials
#  email:            some_mail@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

# Dependencies
markdown:    kramdown
highlighter: rouge

pages_list:
  Archive: '/z_archive'
  RSS Feed: '/atom.xml'
