#  ┌┬┐┌─┐┌─┐   ┬┌─┐┬┌─┬ ┬┬  ┬
#   │││ ││  ── │├┤ ├┴┐└┬┘│  │
#  ─┴┘└─┘└─┘  └┘└─┘┴ ┴ ┴ ┴─┘┴─┘
#_________________________________
#
# Permalinks
#
permalink:           pretty
#relative_permalinks: true

# Setup
#
title:               OpenStreetMap Carto Tutorials
tagline:             'Unofficial documentation'
description:         'Unofficial tutorials for <a href="https://github.com/gravitystorm/openstreetmap-carto" target="_blank">openstreetmap-carto</a>'
url:                 https://ircama.github.io
baseurl:             "/osm-carto-tutorials"
branch:              "gh-pages"
paginate:            4
logo:                "/public/apple-touch-icon-precomposed.png"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style: :compressed

# About/contact
#
author:
  name:              ircama
  url:               https://github.com/ircama
  credits:           '<a href="https://github.com/ircama/osm-carto-tutorials/tree/gh-pages#openstreetmap-carto-tutorials" target="_blank">Credits</a>'
  github_sources:    '<a href="https://github.com/ircama/osm-carto-tutorials/tree/gh-pages" target="_blank">Source</a> on GitHub'
#  email:             my_email@gmail.com

# Custom vars
#
google_search:       011671119207917586318:jtx4jontd8i
google_analytics:    UA-84073284-1
disqus_shortname:    ircama-github-io-osm-carto-tutorials

# Gems
#
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Dependencies
#
markdown:    kramdown
highlighter: rouge

#kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  #input: GFM
  # Disable auto-generated ID's for headings
  #auto_ids: false

pages_list:
  Site map: '/sitemap'
  <i class="iconside iconm-feed2"></i>: '/atom.xml'

collections:
  notes:
    output: true

# HTML Compress - http://jch.penibelst.de/
#
compress_html:
  clippings: all
  blanklines: true
  comments: ['<!-- ', ' -->']
