# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               OpenStreetMap Carto Tutorials
tagline:             'Unofficial documentation'
description:         'Unofficial tutorials for <a href="https://github.com/gravitystorm/openstreetmap-carto" target="_blank">openstreetmap-carto</a>'
url:                 http://ircama.github.io/osm-carto-tutorials
baseurl:             "/osm-carto-tutorials"
paginate:            5

# SEO stuff
google_site_verification: "IFVMiYBt3XHI4p6WW0TQRuTrXop3jVkDuNQVrBkN_CM"
logo:                "{{ site.baseurl }}/public/apple-touch-icon-precomposed.png"

# About/contact
author:
  name:              ircama
  url:               https://github.com/ircama
  credits:           'Built with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> and with a modified <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a> theme. Hosted by <a href="https://github.com" target="_blank">GitHub</a>.'
  github_sources:    <a href="https://github.com/ircama/osm-carto-tutorials/tree/gh-pages" target="_blank">Source on GitHub</a>
#  email:             my_email@gmail.com

# Custom vars
version:             1.0.1
google_search:       011671119207917586318:jtx4jontd8i
google_analytics:    UA-84073284-1
disqus_shortname:    ircama-github-io-osm-carto-tutorials

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Dependencies
markdown:    kramdown
highlighter: rouge

#kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  #input: GFM
  # Disable auto-generated ID's for headings
  #auto_ids: false

pages_list:
  Archive: '/z_archive'
  RSS: '/atom.xml'